name: Gas results readme

on: 
  push:
    branches: 
      - main
    paths:
      - contracts/**
      - tests/**
      - .github/workflows/**

jobs:
  ape-gas:
    runs-on: ubuntu-latest
    name: setup, run and compile ape gas report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: setup ape
        run: |
          pip install eth-ape>=0.6.26
          ape plugins install vyper
          ape plugins install foundry
          ape plugins install hardhat
          npm install hardhat
      - name: Generate gas reports
        run: |
          ape test --network ethereum:local:foundry --gas > foundry-gas-report
          ape test --network ethereum:local:hardhat --gas > hardhat-gas-report
      - name: Update readme with gas results
        run: python gas-readme-update.py
      - name: Commit the new readme
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Update gas report README'
