name: Gas results

on: [push, pull_request]

jobs:
  ape-gas:
    runs-on: ubuntu-latest
    name: setup and run
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install eth-ape>=0.6.26
      - run: ape plugins install foundry
      - run: ape plugins install vyper
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: ape test --network ethereum:local:foundry --gas > gas-report
      - name: Update readme with gas results
        run: python gas-readme-update.py
      - name: Commit the new readme
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Update readme gas results'
