name: Gas results readme

on: 
  push:
    branches: 
      - main
    paths:
      - contracts
      - tests
      - .github/workflows

jobs:
  ape-gas:
    runs-on: ubuntu-latest
    name: setup and run
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install eth-ape>=0.6.26
      - run: ape plugins install vyper
      - run: ape plugins install foundry
      - run: ape plugins install hardhat
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Foundry gas report
        run: ape test --network ethereum:local:foundry --gas > foundry-gas-report
      - name: Install npm and hardhat
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install hardhat
      - name: Hardhat gas report
        run: ape test --network ethereum:local:hardhat --gas > hardhat-gas-report
      - name: Update readme with gas results
        run: python gas-readme-update.py
      - name: Commit the new readme
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Update readme gas results'
